### ISSUE TITLE
[user story title]

### ISSUE THREAD

**Issue by Nika1301** [Nika1301/capstone-project#3]
## Value proposition

As a lucky who is preparing to travel
I want to see form with input fields
in order to create details of my trip

## Description
<img width="323" alt="Traveling Country list" src="https://user-images.githubusercontent.com/54038186/233108984-60efd5cb-a4e5-4265-bce2-bc8190fa49fb.png"> <img width="320" alt="Create your travelin" src="https://user-images.githubusercontent.com/54038186/233104140-e82aad24-48ef-4ef4-9554-04a68bd4a067.png">

## Acceptance criteria

- [ ] Pop-up list of countries available in the 'Country' field 
- [ ] Input field to write city displayed
- [ ] Starting date and end date of the trip available to choose

## Tasks

- [ ] Add Calendar in Next.js
- [ ] Create the component 'CreateCity' 
- [ ] Create Form with fields Country, City, Starting date and end date

Size: M

**Comment by ella-blaupause** [comment]
Nice ✅

**Comment by Nika1301** [comment]
After talking with coach Peter Anderson I changed User story and add more fields on the page.

**Comment by onemanwenttomow** [comment]
LGTM ✅

**Comment by BenRodProd** [comment]
LGTM
