### ISSUE TITLE
User Story3:

### ISSUE THREAD

**Issue by Nika1301** [Nika1301/capstone-project#4]
## Value proposition

As a lucky who is preparing to travel
I want to add some data to the fields: 'Hotel/Apartment'  with days, price and total price,  'Place to visit' with Price, 'Food to try' with price and it should be displayed as a list below the input field
in order to create details of my trip

Description

## Description
<img width="303" alt="Buttons" src="https://user-images.githubusercontent.com/54038186/233336163-5e965d6c-51f2-4528-b358-ba8499e7914d.png">

User can create 'Hotel/Apartment'  with days, price and total price,  'Place to visit' with Price, 'Food to try' with price and can edit and delete it.

## Acceptance criteria

- create buttons 'Add' for the all fields: 'Hotel/Apartment',  'Place to visit',  'Food to try'.
- [ ] data that put in the fields 'Hotel/Apartment'  with days, price and total price displayed as a list below the field after tap on the button 'add' and must to be possible to edit and delete this data.
- [ ] data that put in the fields field 'Place to visit' with Price displayed as a list below the field after tap on the button 'add' and must to be possible to edit and delete this data.
- [ ] data that put in the fields field 'Food to try' with price displayed as a list below the field after tap on the button 'add' and must to be possible to edit and delete this data.
- [ ] data that put in the fields field 'Notes'  displayed 

## Tasks

- [ ] Create components Hotel with props: name, price, total price and edit, delete button
- [ ] Create components PlaceToVisit with props: name, price and edit, delete button
- [ ] Create components FoodToTry with props: name, price and edit, delete button
- [ ] Connect this components to the form

Size: M

**Comment by CJAkkuec** [comment]
Hey there! Nice job, although I'd highly recommend to separate this into three User Stories actually, such as:
User Story 3 - Form, User Story 4 - Edit Entries, User Story 5 - Delete Entries

**Comment by Nika1301** [comment]
After talking with coach Peter Anderson I changed User stories from US1 to US3, with another strategy

**Comment by CJAkkuec** [comment]
Sorry for being annoying and repeating myself, but creating data and editing data should be two User Stories. 🙏 The process of creating a journey should be tested separately from the process of editing data.
