### ISSUE TITLE
User Story 2: Show details of the trip

### ISSUE THREAD

**Issue by Nika1301** [Nika1301/capstone-project#5]
## Value proposition

As a lucky who is preparing to travel
I want to to show all details about my trip 
in order to see information about trip

## Description

<img width="265" alt="DetailsPage" src="https://user-images.githubusercontent.com/54038186/233384467-91c9b166-0aac-476d-945c-7d5a29c07efd.png">

On the  page "Details of trip" shows all information about the trip, buttons "Edit" and "Home"

## Acceptance criteria

- [ ] Country, City(with date), list of hotel, list of places to visit, list of food are displayed
- [ ] Total price for hotel, total price for places, total price for food are displayed. And total price for all fields are displayed
- [ ] Button "Home" navigate to the "All countries" page
- [ ] Button  "Edit" navigate to the "Create traveling" page

## Tasks

- [ ] Show all information about trip: Country, City(with date), list of hotel, list of places to visit, list of food and prices
- [ ] Calculate all prices
- [ ] Create buttons  "Home" and  "Edit" - navigate to the  "All countries" page and "Create traveling" page

Size: M
