### ISSUE TITLE
User Story4: Edit information about the trip

### ISSUE THREAD

**Issue by Nika1301** [Nika1301/capstone-project#6]
## Value proposition

As a lucky who is preparing to travel
I want to edit information about the trip
in order to edit details of my trip

## Description

<img width="341" alt="Edit" src="https://user-images.githubusercontent.com/54038186/233587638-ba27c2fb-aa97-40d1-b141-e2af745acb14.png">

User can edit information of the trip

## Acceptance criteria

- [ ] information about the trip should be possible to edit
- [ ] Items in the lists of the fields must to be possible to edit
- [ ] all information about the trip should be update 

## Tasks

- [ ] create buttons "Edit"  for the fields "Hotel/Apartment", "Place to visit", "Food to try"
- [ ] after click button "Create" - all information about the trip should be update and display

Size: S

**Comment by Nika1301** [comment]
One thing I didn't use edit button for every fields.
